// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/convert": {
            "post": {
                "description": "Converts a value from a base currency to a target currency using the current exchange rate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Converts a value between currencies",
                "parameters": [
                    {
                        "description": "Currency conversion request example",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CurrencySwagger"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/history": {
            "get": {
                "description": "Retrieves the complete history of stored currency conversions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Returns the conversion history",
                "responses": {}
            }
        },
        "/rates/{currency}": {
            "get": {
                "description": "Returns the most recent exchange rate for the requested currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Retrieves the latest exchange rate for a specific currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code (e.g., USD, EUR, BRL)",
                        "name": "currency",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.CurrencySwagger": {
            "type": "object",
            "required": [
                "base_code",
                "conversion_result",
                "target_code"
            ],
            "properties": {
                "base_code": {
                    "type": "string",
                    "example": "BRL"
                },
                "conversion_result": {
                    "type": "number",
                    "example": 250
                },
                "target_code": {
                    "type": "string",
                    "example": "EUR"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Currency Conversion API",
	Description:      "This is an API for currency conversion with historical records.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
